# Generated by Django 5.2.7 on 2025-11-10 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=280)),
                ('address', models.CharField(max_length=280)),
                ('zone', models.CharField(max_length=280)),
                ('deGarde', models.BooleanField(default=False)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specialiste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=280)),
                ('specialite', models.CharField(max_length=280)),
                ('Disponible', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=280)),
                ('categorie', models.CharField(max_length=280)),
                ('description', models.CharField(max_length=280)),
                ('quantite', models.IntegerField()),
                ('prix', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='medicament/')),
                ('pharmacie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tamsPh.pharmacie')),
            ],
        ),
    ]
