# Generated by Django 5.2.7 on 2025-11-19 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tamsPh', '0002_pharmacie_utilisateur'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('reponse', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('type_conversation', models.CharField(choices=[('stock', 'Gestion de Stock'), ('conseil', 'Conseil Client'), ('analyse', 'Analyse et Statistiques'), ('general', 'Question Générale'), ('urgence', "Situation d'Urgence"), ('autre', "pour d'autre questions ou preoccupation")], default='general', max_length=50)),
                ('Pharmacie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mon_ia', to='tamsPh.pharmacie')),
            ],
        ),
    ]
