# Generated by Django 5.2.7 on 2025-11-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tamsPh', '0003_monia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monia',
            name='type_conversation',
            field=models.CharField(choices=[('stock', 'Gestion de Stock'), ('conseil', 'Conseil Client'), ('analyse', 'Analyse et Statistiques'), ('general', 'Question Générale'), ('urgence', "Situation d'Urgence"), ('autre', "pour d'autre questions ou preoccupation")], default='general', max_length=50, verbose_name='Type de Conversation'),
        ),
    ]
