# Generated by Django 5.2.7 on 2025-11-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tamsPh', '0004_alter_monia_type_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialiste',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='personel/'),
        ),
    ]
