# Generated by Django 5.2.7 on 2025-11-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tamsPh', '0005_specialiste_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialiste',
            name='prenom',
            field=models.CharField(default=' ', max_length=280),
        ),
    ]
