# Generated by Django 5.2.7 on 2025-11-25 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tamsPh', '0006_specialiste_prenom'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialiste',
            name='pharmacie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tamsPh.pharmacie'),
        ),
    ]
