# Generated by Django 5.2.7 on 2025-11-28 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tamsPh', '0008_client_commande_lignecommande'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='zone',
            field=models.CharField(default=' ', max_length=280),
        ),
    ]
