# Generated by Django 5.2.7 on 2025-11-29 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tamsPh', '0009_client_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée'), ('expiree', 'Expirée'), ('recuperee', 'Récupérée'), ('annulee', 'Annulée')], default='en_attente', max_length=20),
        ),
    ]
