# Generated by Django 5.2.7 on 2025-11-29 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tamsPh', '0010_alter_commande_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('nouvelle_commande', 'Nouvelle commande'), ('commande_annulee', 'Commande annulée'), ('rappel_stock', 'Rappel de stock bas'), ('alerte_urgence', 'Alerte urgence')], max_length=20)),
                ('message', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('lue', models.BooleanField(default=False)),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tamsPh.commande')),
                ('pharmacie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tamsPh.pharmacie')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
